DROP TABLE PriceThresholds
DROP TABLE Attendees
DROP TABLE Payments
DROP TABLE AttendeesWorkshop
DROP TABLE AttendeesDay
DROP TABLE WorkshopReservations
DROP TABLE DayReservations
DROP TABLE Days
DROP TABLE ConferenceReservations
DROP TABLE Clients
DROP TABLE Workshops
DROP TABLE Conferences
